#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#MISE description="Shell in container (without KAS)"
set -o errexit
set -o nounset
set -o pipefail

# shellcheck source=.mise/tasks/_lib.sh
source "${MISE_CONFIG_ROOT}/.mise/tasks/_lib.sh"
run_in_container --entrypoint /bin/dumb-init -- /bin/bash
