#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#MISE description="Dump KAS configuration for specified BSP"
#USAGE flag "-b --bsp <bsp>" help="BSP target" default="x86_64" {
#USAGE   choices "x86_64" "orin-nx" "rk1" "soquartz"
#USAGE }
set -euo pipefail

BSP="${usage_bsp:-x86_64}"

KAS_CONFIG="${KAS_WORK_DIR}/kas/main.kas.yml:${KAS_WORK_DIR}/kas/bsp/${BSP}.kas.yml"
KAS_DEBUG="${KAS_WORK_DIR}/kas/extras/debug.kas.yml"

source "${LAMADIST_PROJECT_DIR}/.mise/tasks/_lib.sh"
run_in_container dump "${KAS_CONFIG}:${KAS_DEBUG}"
