#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#MISE description="Interactive KAS shell for specified BSP"
#USAGE flag "-b --bsp <bsp>" help="BSP target" default="x86_64" {
#USAGE   choices "x86_64" "orin-nx" "rk1" "soquartz"
#USAGE }
set -o errexit
set -o nounset
set -o pipefail

_bsp="${usage_bsp:-x86_64}"

_kas_config="${KAS_WORK_DIR}/kas/main.kas.yml:${KAS_WORK_DIR}/kas/bsp/${_bsp}.kas.yml"
_kas_debug="${KAS_WORK_DIR}/kas/extras/debug.kas.yml"

# shellcheck source=.mise/tasks/_lib.sh
source "${MISE_CONFIG_ROOT}/.mise/tasks/_lib.sh"
run_in_container shell "${_kas_config}:${_kas_debug}"
