# SPDX-License-Identifier: Apache-2.0
# Persist the journal on the writable /var partition; journald
# creates /var/log/journal itself when Storage=persistent.
[Journal]
Storage=persistent
SystemMaxUse=256M
