#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#MISE description="Remove container image"
set -o errexit
set -o nounset
set -o pipefail
"${LAMADIST_CONTAINER_CMD}" rmi "${LAMADIST_CONTAINER_IMAGE}" || true
echo "Removed container image."
